simulation:
  # file containing regions that are to be simulated using nanosim
  regions: "config/simulation/simulation_regions.tsv"

  reference: &ref
    name: "genome"
    path: "resources/genome.fasta"

  # construct nanosim error model from this sample
  error_model:
    name: "kelly"
    sample: "data/kelly.fastq.gz"

  wgs_noise:
    coverage: 1.00
    
  # simulate regions at the given target coverages
  target_coverages: [5, 6, 7, 8, 9, 10, 15, 20]
